"""Purchased open-ended 2 mm pitch belt and screwless V4 terminations.

The model is an interface envelope, not a flexible-material simulation.  Belt
backing and transverse teeth are deliberately separate closed BREP solids.
The reel axis is +Z and the straight run stays centred at ``BELT_Z``.
"""

from dataclasses import dataclass
from math import ceil, cos, degrees, floor, pi, sin
from typing import List, Sequence, Tuple

from build123d import Align, Axis, Box, Compound, Cylinder, Location, Shape

from v4_kinematics import BELT_PITCH, BELT_Z, REEL_PITCH_RADIUS, REEL_TEETH, pose_state


BELT_WIDTH = 12.0
BACKING_THICKNESS = 1.2
TOOTH_DEPTH = 0.9
TOOTH_TANGENTIAL_LENGTH = 0.80

# A purchased open belt has 11 teeth on the reel at the zero pose.  Five are
# retained by the removable wedge, leaving six working grooves engaged.
INITIAL_WRAP_TEETH = 11
WEDGE_CAPTURE_TEETH = 5
BACKING_INNER_RADIUS = REEL_PITCH_RADIUS + 0.30
DRUM_OUTER_RADIUS = REEL_PITCH_RADIUS - 0.25
DRUM_ROOT_RADIUS = REEL_PITCH_RADIUS - 1.10
ARC_CHORD_STEP_DEG = 5.0
POCKET_CLEARANCE = 0.06
CONTACT_TOLERANCE = 1e-6


@dataclass(frozen=True)
class ReelEngagementReport:
    engaged_teeth: int
    occupied_grooves: int
    positive_penetration_volume: float


@dataclass(frozen=True)
class BeltRetentionReport:
    reel_wedge_captured_teeth: int
    slider_wedge_captured_teeth: int
    reel_wedge_at_datum: bool
    slider_wedge_at_datum: bool
    reel_working_direction_blocked: bool
    slider_working_direction_blocked: bool


def _box(size: Tuple[float, float, float], center: Tuple[float, float, float]) -> Shape:
    return Box(*size, align=(Align.CENTER, Align.CENTER, Align.CENTER)).moved(Location(center))


def _polar_box(
    radial_center: float,
    angle: float,
    radial_size: float,
    tangential_size: float,
    z_size: float = BELT_WIDTH,
    z_center: float = BELT_Z,
) -> Shape:
    shape = _box((radial_size, tangential_size, z_size), (0.0, 0.0, z_center))
    shape = shape.rotate(Axis.Z, degrees(angle))
    return shape.moved(Location((radial_center * cos(angle), radial_center * sin(angle), 0.0)))


def _label(shape: Shape, label: str) -> Shape:
    shape.label = label
    return shape


def _compound(label: str, children: Sequence[Shape]) -> Compound:
    result = Compound(label=label, children=list(children))
    result.label = label
    return result


def _phase(travel: float) -> float:
    """World-space tooth phase generated by the kinematic reel rotation."""
    return pose_state(travel).reel_angle_rad


def _wrapped_tooth_count(travel: float) -> int:
    wrap_length = INITIAL_WRAP_TEETH * BELT_PITCH + pose_state(travel).belt_feed
    return floor(wrap_length / BELT_PITCH + 1e-9)


def _arc_tooth_angles(travel: float) -> List[float]:
    pitch_angle = BELT_PITCH / REEL_PITCH_RADIUS
    phase = _phase(travel)
    return [pi - phase - (index + 0.5) * pitch_angle for index in range(_wrapped_tooth_count(travel))]


def _arc_tooth(angle: float, clearance: float = 0.0) -> Shape:
    radial_center = BACKING_INNER_RADIUS - TOOTH_DEPTH / 2.0
    return _polar_box(
        radial_center,
        angle,
        TOOTH_DEPTH + 2.0 * clearance,
        TOOTH_TANGENTIAL_LENGTH + 2.0 * clearance,
        BELT_WIDTH + 2.0 * clearance,
    )


def _groove(angle: float) -> Shape:
    radial_center = (DRUM_ROOT_RADIUS + BACKING_INNER_RADIUS + POCKET_CLEARANCE) / 2.0
    return _polar_box(
        radial_center,
        angle,
        BACKING_INNER_RADIUS + POCKET_CLEARANCE - DRUM_ROOT_RADIUS,
        TOOTH_TANGENTIAL_LENGTH + 2.0 * POCKET_CLEARANCE,
        BELT_WIDTH + 1.0,
    )


def _all_grooves(travel: float) -> List[Shape]:
    pitch_angle = BELT_PITCH / REEL_PITCH_RADIUS
    phase = _phase(travel)
    return [_groove(pi - phase - (index + 0.5) * pitch_angle) for index in range(REEL_TEETH)]


def _reel_capture_angles(travel: float) -> List[float]:
    return _arc_tooth_angles(travel)[-WEDGE_CAPTURE_TEETH:]


def _reel_wedge_outer_cells(travel: float) -> List[Shape]:
    # Overlapping cells form a tapered/undercut strip around five tooth roots.
    cells = []
    angles = _reel_capture_angles(travel)
    for index, angle in enumerate(angles):
        taper = 0.10 * index / max(1, len(angles) - 1)
        cells.append(
            _polar_box(
                BACKING_INNER_RADIUS - 0.52,
                angle,
                1.10 + taper,
                BELT_PITCH + 0.18,
            )
        )
    return cells


def _reel_wedge_and_pockets(travel: float) -> Tuple[Shape, List[Shape]]:
    outer_cells = _reel_wedge_outer_cells(travel)
    wedge = outer_cells[0]
    for cell in outer_cells[1:]:
        wedge = wedge + cell
    pockets = [_arc_tooth(angle, POCKET_CLEARANCE) for angle in _reel_capture_angles(travel)]
    for pocket in pockets:
        wedge = wedge - pocket
    return _label(wedge, "reel_end_tooth_wedge"), pockets


def _reel_pocket_support(travel: float) -> Tuple[Shape, Shape]:
    angles = _reel_capture_angles(travel)
    mid_angle = sum(angles) / len(angles)
    angular_span = abs(angles[-1] - angles[0])
    tangent_length = REEL_PITCH_RADIUS * angular_span + BELT_PITCH + 0.3
    # The floor is connected radially to the drum and its top is the insertion datum.
    floor = _polar_box(
        (DRUM_ROOT_RADIUS + BACKING_INNER_RADIUS) / 2.0,
        mid_angle,
        BACKING_INNER_RADIUS - DRUM_ROOT_RADIUS + 0.6,
        tangent_length,
        0.8,
        BELT_Z - BELT_WIDTH / 2.0 - 0.4,
    )
    # A tangential shoulder at the loaded end makes belt tension self-tightening.
    stop_angle = angles[-1]
    stop_thickness = 0.18
    wedge_cell_length = BELT_PITCH + 0.18
    tangent_offset = (wedge_cell_length + stop_thickness) / 2.0
    radius = BACKING_INNER_RADIUS - 0.52
    stop = _box((1.3, stop_thickness, BELT_WIDTH), (0.0, 0.0, BELT_Z))
    stop = stop.rotate(Axis.Z, degrees(stop_angle))
    stop = stop.moved(
        Location(
            (
                radius * cos(stop_angle) + tangent_offset * sin(stop_angle),
                radius * sin(stop_angle) - tangent_offset * cos(stop_angle),
                0.0,
            )
        )
    )
    return floor, stop


def _reel_drum(travel: float) -> Shape:
    drum = Cylinder(
        DRUM_OUTER_RADIUS,
        BELT_WIDTH,
        align=(Align.CENTER, Align.CENTER, Align.MIN),
    ).moved(Location((0.0, 0.0, BELT_Z - BELT_WIDTH / 2.0)))
    for groove in _all_grooves(travel):
        drum = drum - groove
    # A broad radial pocket replaces five ordinary lands at the service end.
    for cell in _reel_wedge_outer_cells(travel):
        drum = drum - cell
    floor, stop = _reel_pocket_support(travel)
    drum = drum + floor + stop
    return _label(drum, "reel_drum_41t")


def _arc_backing(travel: float) -> List[Shape]:
    wrap_angle = (INITIAL_WRAP_TEETH * BELT_PITCH + pose_state(travel).belt_feed) / REEL_PITCH_RADIUS
    count = max(1, ceil(degrees(wrap_angle) / ARC_CHORD_STEP_DEG))
    delta = wrap_angle / count
    radius = BACKING_INNER_RADIUS + BACKING_THICKNESS / 2.0
    phase = _phase(travel)
    return [
        _polar_box(
            radius,
            pi - phase - (index + 0.5) * delta,
            BACKING_THICKNESS,
            radius * delta * 1.02,
        )
        for index in range(count)
    ]


def _straight_backing(travel: float) -> Shape:
    length = pose_state(travel).free_belt_length
    return _box(
        (BACKING_THICKNESS, length, BELT_WIDTH),
        (-(BACKING_INNER_RADIUS + BACKING_THICKNESS / 2.0), -length / 2.0, BELT_Z),
    )


def _straight_teeth(travel: float) -> List[Shape]:
    length = pose_state(travel).free_belt_length
    count = floor(length / BELT_PITCH)
    residual_phase = pose_state(travel).belt_feed % BELT_PITCH
    radial_center = -(BACKING_INNER_RADIUS - TOOTH_DEPTH / 2.0)
    result = []
    for index in range(count):
        y = -residual_phase - (index + 0.5) * BELT_PITCH
        if y - TOOTH_TANGENTIAL_LENGTH / 2.0 >= -length:
            result.append(_box((TOOTH_DEPTH, TOOTH_TANGENTIAL_LENGTH, BELT_WIDTH), (radial_center, y, BELT_Z)))
    return result


def _slider_capture_teeth(travel: float) -> List[Shape]:
    return _straight_teeth(travel)[-WEDGE_CAPTURE_TEETH:]


def _slider_wedge_and_pockets(travel: float) -> Tuple[Shape, List[Shape]]:
    teeth = _slider_capture_teeth(travel)
    centers = [tooth.bounding_box().center() for tooth in teeth]
    y_center = sum(center.Y for center in centers) / len(centers)
    y_span = max(center.Y for center in centers) - min(center.Y for center in centers) + BELT_PITCH
    wedge = _box((1.65, y_span, BELT_WIDTH), (-(BACKING_INNER_RADIUS - 0.62), y_center, BELT_Z))
    pockets = []
    for tooth in teeth:
        center = tooth.bounding_box().center()
        pocket = _box(
            (TOOTH_DEPTH + 2 * POCKET_CLEARANCE, TOOTH_TANGENTIAL_LENGTH + 2 * POCKET_CLEARANCE, BELT_WIDTH + 0.4),
            (center.X, center.Y, center.Z),
        )
        pockets.append(pocket)
        wedge = wedge - pocket
    return _label(wedge, "slider_end_tooth_wedge"), pockets


def _slider_support(travel: float) -> Tuple[Shape, Shape, Shape]:
    teeth = _slider_capture_teeth(travel)
    y_values = [tooth.bounding_box().center().Y for tooth in teeth]
    y_center = sum(y_values) / len(y_values)
    y_span = max(y_values) - min(y_values) + BELT_PITCH
    # U-shaped captured slot: an X seating wall, two Z rails, and a load-end wall.
    wedge_x_center = -(BACKING_INNER_RADIUS - 0.62)
    wedge_x_max = wedge_x_center + 1.65 / 2.0
    datum_wall = _box(
        (0.8, y_span + 3.0, BELT_WIDTH + 4.0),
        (wedge_x_max + 0.4, y_center, BELT_Z),
    )
    lower_rail = _box((4.6, y_span + 3.0, 1.0), (-13.825, y_center, BELT_Z - BELT_WIDTH / 2.0 - 0.5))
    upper_rail = _box((4.6, y_span + 3.0, 1.0), (-13.825, y_center, BELT_Z + BELT_WIDTH / 2.0 + 0.5))
    load_stop_y = y_center - y_span / 2.0 - 0.2
    load_stop = _box((4.6, 0.4, BELT_WIDTH + 2.0), (-13.825, load_stop_y, BELT_Z))
    slider = datum_wall + lower_rail + upper_rail + load_stop
    return _label(slider, "screwless_belt_end_slider"), datum_wall, load_stop


def build_belt_system(travel: float) -> Compound:
    """Build the purchased-belt envelope and two removable tooth wedges."""
    pose_state(travel)  # public range validation and single source of truth
    backing = _compound("flexible_belt_backing", [_straight_backing(travel), *_arc_backing(travel)])
    teeth = _compound(
        "flexible_belt_teeth",
        [*_straight_teeth(travel), *[_arc_tooth(angle) for angle in _arc_tooth_angles(travel)]],
    )
    reel_wedge, _ = _reel_wedge_and_pockets(travel)
    slider_wedge, _ = _slider_wedge_and_pockets(travel)
    children = [
        backing,
        teeth,
        _reel_drum(travel),
        reel_wedge,
        _slider_support(travel)[0],
        slider_wedge,
    ]
    return _compound(f"v4_serviceable_belt_system_t{travel:.3f}", children)


def reel_engagement_report(travel: float) -> ReelEngagementReport:
    """Count real tooth/groove BREP occupancy and positive land penetration."""
    pose_state(travel)
    capture_angles = set(_reel_capture_angles(travel))
    tooth_angles = [angle for angle in _arc_tooth_angles(travel) if angle not in capture_angles]
    grooves = _all_grooves(travel)
    drum = _reel_drum(travel)
    engaged = 0
    occupied = set()
    penetration = 0.0
    for angle in tooth_angles:
        tooth = _arc_tooth(angle)
        overlaps = [(tooth & groove).volume for groove in grooves]
        groove_index = max(range(len(overlaps)), key=overlaps.__getitem__)
        if overlaps[groove_index] >= tooth.volume * 0.95:
            engaged += 1
            occupied.add(groove_index)
        penetration += (tooth & drum).volume
    return ReelEngagementReport(engaged, len(occupied), penetration)


def _occupied_pocket_count(teeth: Sequence[Shape], pockets: Sequence[Shape]) -> int:
    occupied = 0
    for tooth in teeth:
        if max((tooth & pocket).volume for pocket in pockets) >= tooth.volume * 0.95:
            occupied += 1
    return occupied


def belt_retention_report() -> BeltRetentionReport:
    """Measure nominal-pose tooth-pocket occupancy and physical seating faces."""
    travel = 0.5
    reel_teeth = [_arc_tooth(angle) for angle in _reel_capture_angles(travel)]
    reel_wedge, reel_pockets = _reel_wedge_and_pockets(travel)
    reel_floor, reel_stop = _reel_pocket_support(travel)
    slider_teeth = _slider_capture_teeth(travel)
    slider_wedge, slider_pockets = _slider_wedge_and_pockets(travel)
    _, slider_datum, slider_stop = _slider_support(travel)

    reel_box = reel_wedge.bounding_box()
    floor_box = reel_floor.bounding_box()
    slider_box = slider_wedge.bounding_box()
    datum_box = slider_datum.bounding_box()
    return BeltRetentionReport(
        reel_wedge_captured_teeth=_occupied_pocket_count(reel_teeth, reel_pockets),
        slider_wedge_captured_teeth=_occupied_pocket_count(slider_teeth, slider_pockets),
        reel_wedge_at_datum=abs(reel_box.min.Z - floor_box.max.Z) <= CONTACT_TOLERANCE,
        slider_wedge_at_datum=abs(slider_box.max.X - datum_box.min.X) <= CONTACT_TOLERANCE,
        reel_working_direction_blocked=(
            reel_wedge.distance_to(reel_stop) <= CONTACT_TOLERANCE
            and (reel_wedge & reel_stop).volume <= CONTACT_TOLERANCE
        ),
        slider_working_direction_blocked=(
            slider_wedge.distance_to(slider_stop) <= CONTACT_TOLERANCE
            and (slider_wedge & slider_stop).volume <= CONTACT_TOLERANCE
        ),
    )


def gen_step() -> Compound:
    """CAD-skill source envelope; Task 2 intentionally does not export STEP."""
    return build_belt_system(0.5)
