"""Purchased open-ended 2 mm pitch belt and screwless V4 terminations.

The model is an interface envelope, not a flexible-material simulation.  Belt
backing and transverse teeth are deliberately separate closed BREP solids.
The reel axis is +Z and the straight run stays centred at ``BELT_Z``.
"""

from dataclasses import dataclass
from math import atan2, ceil, cos, degrees, pi, sin
from typing import List, Sequence, Tuple

from build123d import Align, Axis, Box, Compound, Cylinder, Location, Shape

from v4_kinematics import (
    BELT_PITCH,
    BELT_Z,
    INITIAL_WRAP_TEETH,
    REEL_PITCH_RADIUS,
    REEL_TEETH,
    pose_state,
)


BELT_WIDTH = 12.0
BACKING_THICKNESS = 1.2
TOOTH_DEPTH = 0.9
TOOTH_TANGENTIAL_LENGTH = 0.80

WEDGE_CAPTURE_TEETH = 5
BACKING_INNER_RADIUS = REEL_PITCH_RADIUS + 0.30
DRUM_OUTER_RADIUS = REEL_PITCH_RADIUS - 0.25
DRUM_ROOT_RADIUS = REEL_PITCH_RADIUS - 1.10
ARC_CHORD_STEP_DEG = 5.0
POCKET_CLEARANCE = 0.06
CONTACT_TOLERANCE = 1e-6


@dataclass(frozen=True)
class ReelEngagementReport:
    engaged_teeth: int
    occupied_grooves: int
    positive_penetration_volume: float


@dataclass(frozen=True)
class BeltRetentionReport:
    reel_wedge_captured_teeth: int
    slider_wedge_captured_teeth: int
    reel_wedge_at_datum: bool
    slider_wedge_at_datum: bool
    reel_working_direction_blocked: bool
    slider_working_direction_blocked: bool


@dataclass(frozen=True)
class BeltPathReport:
    centerline_length: float
    backing_entry_gap: float


@dataclass(frozen=True)
class SliderWedgeInsertionReport:
    insertion_direction: str
    samples: int
    max_positive_collision_volume: float
    final_at_datum: bool


@dataclass(frozen=True)
class TangentToothPitchReport:
    straight_nearest_center_offset: float
    wrapped_nearest_center_offset: float
    tangent_center_pitch: float
    total_tooth_solids: int


def _box(size: Tuple[float, float, float], center: Tuple[float, float, float]) -> Shape:
    return Box(*size, align=(Align.CENTER, Align.CENTER, Align.CENTER)).moved(Location(center))


def _polar_box(
    radial_center: float,
    angle: float,
    radial_size: float,
    tangential_size: float,
    z_size: float = BELT_WIDTH,
    z_center: float = BELT_Z,
) -> Shape:
    shape = _box((radial_size, tangential_size, z_size), (0.0, 0.0, z_center))
    shape = shape.rotate(Axis.Z, degrees(angle))
    return shape.moved(Location((radial_center * cos(angle), radial_center * sin(angle), 0.0)))


def _label(shape: Shape, label: str) -> Shape:
    shape.label = label
    return shape


def _compound(label: str, children: Sequence[Shape]) -> Compound:
    result = Compound(label=label, children=list(children))
    result.label = label
    return result


def _phase(travel: float) -> float:
    """World-space tooth phase generated by the kinematic reel rotation."""
    return pose_state(travel).reel_angle_rad


def _clockwise_from_entry(angle: float) -> float:
    return (pi - angle) % (2.0 * pi)


def _wrap_angle(travel: float) -> float:
    return (INITIAL_WRAP_TEETH * BELT_PITCH + pose_state(travel).belt_feed) / REEL_PITCH_RADIUS


def _wrapped_tooth_count(travel: float) -> int:
    return len(_arc_tooth_angles(travel))


def _arc_tooth_angles(travel: float) -> List[float]:
    # The belt entry is fixed in world space. Select the rotating reel grooves
    # that physically lie inside the current entry-to-wrap angular window.
    wrap_angle = _wrap_angle(travel)
    angles = [
        angle
        for angle in _all_groove_angles(travel)
        if CONTACT_TOLERANCE < _clockwise_from_entry(angle) < wrap_angle - CONTACT_TOLERANCE
    ]
    return sorted(angles, key=_clockwise_from_entry)


def _arc_tooth(angle: float, clearance: float = 0.0) -> Shape:
    radial_center = BACKING_INNER_RADIUS - TOOTH_DEPTH / 2.0
    return _polar_box(
        radial_center,
        angle,
        TOOTH_DEPTH + 2.0 * clearance,
        TOOTH_TANGENTIAL_LENGTH + 2.0 * clearance,
        BELT_WIDTH + 2.0 * clearance,
    )


def _groove(angle: float) -> Shape:
    radial_center = (DRUM_ROOT_RADIUS + BACKING_INNER_RADIUS + POCKET_CLEARANCE) / 2.0
    return _polar_box(
        radial_center,
        angle,
        BACKING_INNER_RADIUS + POCKET_CLEARANCE - DRUM_ROOT_RADIUS,
        TOOTH_TANGENTIAL_LENGTH + 2.0 * POCKET_CLEARANCE,
        BELT_WIDTH + 1.0,
    )


def _all_groove_angles(travel: float) -> List[float]:
    pitch_angle = BELT_PITCH / REEL_PITCH_RADIUS
    phase = _phase(travel)
    return [pi - phase - (index + 0.5) * pitch_angle for index in range(REEL_TEETH)]


def _all_grooves(travel: float) -> List[Shape]:
    return [_groove(angle) for angle in _all_groove_angles(travel)]


def _reel_capture_angles(travel: float) -> List[float]:
    return _arc_tooth_angles(travel)[-WEDGE_CAPTURE_TEETH:]


def _reel_wedge_outer_cells(travel: float) -> List[Shape]:
    # Overlapping cells form a tapered/undercut strip around five tooth roots.
    cells = []
    angles = _reel_capture_angles(travel)
    for index, angle in enumerate(angles):
        taper = 0.10 * index / max(1, len(angles) - 1)
        cells.append(
            _polar_box(
                BACKING_INNER_RADIUS - 0.52,
                angle,
                1.10 + taper,
                BELT_PITCH + 0.18,
            )
        )
    return cells


def _reel_wedge_and_pockets(travel: float) -> Tuple[Shape, List[Shape]]:
    outer_cells = _reel_wedge_outer_cells(travel)
    wedge = outer_cells[0]
    for cell in outer_cells[1:]:
        wedge = wedge + cell
    pockets = [_arc_tooth(angle, POCKET_CLEARANCE) for angle in _reel_capture_angles(travel)]
    for pocket in pockets:
        wedge = wedge - pocket
    return _label(wedge, "reel_end_tooth_wedge"), pockets


def _reel_pocket_support(travel: float) -> Tuple[Shape, Shape]:
    angles = _reel_capture_angles(travel)
    mid_angle = sum(angles) / len(angles)
    angular_span = abs(angles[-1] - angles[0])
    tangent_length = REEL_PITCH_RADIUS * angular_span + BELT_PITCH + 0.3
    # The floor is connected radially to the drum and its top is the insertion datum.
    floor = _polar_box(
        (DRUM_ROOT_RADIUS + BACKING_INNER_RADIUS) / 2.0,
        mid_angle,
        BACKING_INNER_RADIUS - DRUM_ROOT_RADIUS + 0.6,
        tangent_length,
        0.8,
        BELT_Z - BELT_WIDTH / 2.0 - 0.4,
    )
    # A tangential shoulder at the loaded end makes belt tension self-tightening.
    stop_angle = angles[0]
    stop_thickness = 0.18
    wedge_cell_length = BELT_PITCH + 0.18
    tangent_offset = (wedge_cell_length + stop_thickness) / 2.0
    radius = BACKING_INNER_RADIUS - 0.52
    stop = _box((1.3, stop_thickness, BELT_WIDTH), (0.0, 0.0, BELT_Z))
    stop = stop.rotate(Axis.Z, degrees(stop_angle))
    stop = stop.moved(
        Location(
            (
                radius * cos(stop_angle) - tangent_offset * sin(stop_angle),
                radius * sin(stop_angle) + tangent_offset * cos(stop_angle),
                0.0,
            )
        )
    )
    return floor, stop


def _reel_drum(travel: float) -> Shape:
    drum = Cylinder(
        DRUM_OUTER_RADIUS,
        BELT_WIDTH,
        align=(Align.CENTER, Align.CENTER, Align.MIN),
    ).moved(Location((0.0, 0.0, BELT_Z - BELT_WIDTH / 2.0)))
    for groove in _all_grooves(travel):
        drum = drum - groove
    # A broad radial pocket replaces five ordinary lands at the service end.
    for cell in _reel_wedge_outer_cells(travel):
        drum = drum - cell
    floor, stop = _reel_pocket_support(travel)
    drum = drum + floor + stop
    return _label(drum, "reel_drum_41t")


def _arc_backing(travel: float) -> List[Shape]:
    wrap_angle = _wrap_angle(travel)
    count = max(1, ceil(degrees(wrap_angle) / ARC_CHORD_STEP_DEG))
    delta = wrap_angle / count
    radius = BACKING_INNER_RADIUS + BACKING_THICKNESS / 2.0
    return [
        _polar_box(
            radius,
            pi - (index + 0.5) * delta,
            BACKING_THICKNESS,
            radius * delta * 1.02,
        )
        for index in range(count)
    ]


def _straight_backing(travel: float) -> Shape:
    length = pose_state(travel).free_belt_length
    return _box(
        (BACKING_THICKNESS, length, BELT_WIDTH),
        (-(BACKING_INNER_RADIUS + BACKING_THICKNESS / 2.0), -length / 2.0, BELT_Z),
    )


def _straight_teeth(travel: float) -> List[Shape]:
    length = pose_state(travel).free_belt_length
    wrapped_offset = min(
        REEL_PITCH_RADIUS * _clockwise_from_entry(angle) for angle in _arc_tooth_angles(travel)
    )
    nearest_offset = (-wrapped_offset) % BELT_PITCH
    radial_center = -(BACKING_INNER_RADIUS - TOOTH_DEPTH / 2.0)
    backing_bounds = _straight_backing(travel).bounding_box()
    result = []
    # Generate one extra boundary candidate, then retain it only if its actual
    # tooth BREP fits completely on the posed straight backing.
    for index in range(ceil(length / BELT_PITCH) + 1):
        y = -nearest_offset - index * BELT_PITCH
        tooth = _box((TOOTH_DEPTH, TOOTH_TANGENTIAL_LENGTH, BELT_WIDTH), (radial_center, y, BELT_Z))
        bounds = tooth.bounding_box()
        if (
            bounds.min.Y >= backing_bounds.min.Y - CONTACT_TOLERANCE
            and bounds.max.Y <= backing_bounds.max.Y + CONTACT_TOLERANCE
        ):
            result.append(tooth)
    return result


def _slider_capture_teeth(travel: float) -> List[Shape]:
    return _straight_teeth(travel)[-WEDGE_CAPTURE_TEETH:]


def _slider_wedge_and_pockets(travel: float) -> Tuple[Shape, List[Shape]]:
    teeth = _slider_capture_teeth(travel)
    centers = [tooth.bounding_box().center() for tooth in teeth]
    y_center = sum(center.Y for center in centers) / len(centers)
    y_span = max(center.Y for center in centers) - min(center.Y for center in centers) + BELT_PITCH
    # The wedge approaches from +X. Tooth slots break through its leading -X
    # face but stop before the +X back wall; integral Z rails remain above and
    # below the full-width belt teeth.
    wedge_x_min = -BACKING_INNER_RADIUS
    wedge_x_size = 1.70
    wedge = _box(
        (wedge_x_size, y_span, BELT_WIDTH + 2.0),
        (wedge_x_min + wedge_x_size / 2.0, y_center, BELT_Z),
    )
    pockets = []
    for tooth in teeth:
        tooth_box = tooth.bounding_box()
        center = tooth_box.center()
        pocket_x_min = wedge_x_min - 0.10
        pocket_x_max = tooth_box.max.X + POCKET_CLEARANCE
        pocket = _box(
            (
                pocket_x_max - pocket_x_min,
                TOOTH_TANGENTIAL_LENGTH + 2 * POCKET_CLEARANCE,
                BELT_WIDTH + 2 * POCKET_CLEARANCE,
            ),
            ((pocket_x_min + pocket_x_max) / 2.0, center.Y, center.Z),
        )
        pockets.append(pocket)
        wedge = wedge - pocket
    return _label(wedge, "slider_end_tooth_wedge"), pockets


def _slider_support(travel: float) -> Tuple[Shape, Shape, Shape]:
    teeth = _slider_capture_teeth(travel)
    y_values = [tooth.bounding_box().center().Y for tooth in teeth]
    y_center = sum(y_values) / len(y_values)
    y_span = max(y_values) - min(y_values) + BELT_PITCH
    # Open +X approach corridor, left seating wall, upper/lower Z capture rails,
    # and a -Y load wall. No solid closes the transverse insertion path.
    wedge_x_min = -BACKING_INNER_RADIUS
    wedge_x_max = wedge_x_min + 1.70
    datum_wall = _box(
        (0.8, y_span + 3.0, BELT_WIDTH + 4.0),
        (wedge_x_min - 0.4, y_center, BELT_Z),
    )
    corridor_x_center = (wedge_x_min - 0.8 + wedge_x_max + 3.0) / 2.0
    corridor_x_size = wedge_x_max + 3.0 - (wedge_x_min - 0.8)
    lower_rail = _box(
        (corridor_x_size, y_span + 3.0, 1.0),
        (corridor_x_center, y_center, BELT_Z - BELT_WIDTH / 2.0 - 1.5),
    )
    upper_rail = _box(
        (corridor_x_size, y_span + 3.0, 1.0),
        (corridor_x_center, y_center, BELT_Z + BELT_WIDTH / 2.0 + 1.5),
    )
    load_stop_y = y_center + y_span / 2.0 + 0.2
    load_stop = _box((corridor_x_size, 0.4, BELT_WIDTH + 2.0), (corridor_x_center, load_stop_y, BELT_Z))
    slider = datum_wall + lower_rail + upper_rail + load_stop
    return _label(slider, "screwless_belt_end_slider"), datum_wall, load_stop


def build_belt_system(travel: float) -> Compound:
    """Build the purchased-belt envelope and two removable tooth wedges."""
    pose_state(travel)  # public range validation and single source of truth
    backing = _compound("flexible_belt_backing", [_straight_backing(travel), *_arc_backing(travel)])
    teeth = _compound(
        "flexible_belt_teeth",
        [*_straight_teeth(travel), *[_arc_tooth(angle) for angle in _arc_tooth_angles(travel)]],
    )
    reel_wedge, _ = _reel_wedge_and_pockets(travel)
    slider_wedge, _ = _slider_wedge_and_pockets(travel)
    children = [
        backing,
        teeth,
        _reel_drum(travel),
        reel_wedge,
        _slider_support(travel)[0],
        slider_wedge,
    ]
    return _compound(f"v4_serviceable_belt_system_t{travel:.3f}", children)


def reel_engagement_report(travel: float) -> ReelEngagementReport:
    """Count real tooth/groove BREP occupancy and positive land penetration."""
    pose_state(travel)
    capture_angles = set(_reel_capture_angles(travel))
    tooth_angles = [angle for angle in _arc_tooth_angles(travel) if angle not in capture_angles]
    grooves = _all_grooves(travel)
    drum = _reel_drum(travel)
    engaged = 0
    occupied = set()
    penetration = 0.0
    for angle in tooth_angles:
        tooth = _arc_tooth(angle)
        overlaps = [(tooth & groove).volume for groove in grooves]
        groove_index = max(range(len(overlaps)), key=overlaps.__getitem__)
        if overlaps[groove_index] >= tooth.volume * 0.95:
            engaged += 1
            occupied.add(groove_index)
        penetration += (tooth & drum).volume
    return ReelEngagementReport(engaged, len(occupied), penetration)


def belt_path_report(travel: float) -> BeltPathReport:
    """Measure fixed-entry continuity and pitch-line length from posed BREP."""
    straight = _straight_backing(travel)
    arc = _arc_backing(travel)
    centers = [segment.bounding_box().center() for segment in arc]
    distances = sorted(_clockwise_from_entry(atan2(c.Y, c.X)) for c in centers)
    segment_angle = distances[1] - distances[0] if len(distances) > 1 else _wrap_angle(travel)
    measured_wrap_angle = distances[-1] - distances[0] + segment_angle
    straight_length = straight.bounding_box().max.Y - straight.bounding_box().min.Y
    return BeltPathReport(
        centerline_length=straight_length + REEL_PITCH_RADIUS * measured_wrap_angle,
        backing_entry_gap=straight.distance_to(arc[0]),
    )


def tangent_tooth_pitch_report(travel: float) -> TangentToothPitchReport:
    """Measure tooth-center pitch across the fixed straight/arc tangent."""
    straight_teeth = _straight_teeth(travel)
    wrapped_teeth = [_arc_tooth(angle) for angle in _arc_tooth_angles(travel)]
    straight_offset = min(-tooth.bounding_box().center().Y for tooth in straight_teeth)
    wrapped_offset = min(
        REEL_PITCH_RADIUS
        * _clockwise_from_entry(
            atan2(tooth.bounding_box().center().Y, tooth.bounding_box().center().X)
        )
        for tooth in wrapped_teeth
    )
    return TangentToothPitchReport(
        straight_nearest_center_offset=straight_offset,
        wrapped_nearest_center_offset=wrapped_offset,
        tangent_center_pitch=straight_offset + wrapped_offset,
        total_tooth_solids=len(straight_teeth) + len(wrapped_teeth),
    )


def _reel_load_probes(angles: Sequence[float]) -> List[Shape]:
    probes = []
    probe_length = 0.20
    radial_center = BACKING_INNER_RADIUS - TOOTH_DEPTH / 2.0
    tangent_offset = TOOTH_TANGENTIAL_LENGTH / 2.0 + POCKET_CLEARANCE + probe_length / 2.0
    for angle in angles:
        probe = _box((TOOTH_DEPTH * 0.8, probe_length, BELT_WIDTH * 0.8), (0.0, 0.0, BELT_Z))
        probe = probe.rotate(Axis.Z, degrees(angle))
        probe = probe.moved(
            Location(
                (
                    radial_center * cos(angle) - tangent_offset * sin(angle),
                    radial_center * sin(angle) + tangent_offset * cos(angle),
                    0.0,
                )
            )
        )
        probes.append(probe)
    return probes


def _slider_load_probes(teeth: Sequence[Shape]) -> List[Shape]:
    probes = []
    probe_length = 0.20
    for tooth in teeth:
        bounds = tooth.bounding_box()
        probes.append(
            _box(
                (TOOTH_DEPTH * 0.8, probe_length, BELT_WIDTH * 0.8),
                (
                    bounds.center().X,
                    bounds.max.Y + POCKET_CLEARANCE + probe_length / 2.0,
                    BELT_Z,
                ),
            )
        )
    return probes


def _captured_tooth_count(
    teeth: Sequence[Shape],
    pockets: Sequence[Shape],
    wedge: Shape,
    load_probes: Sequence[Shape],
) -> int:
    """Count only occupied, collision-free cavities with real load-side lands."""
    captured = 0
    for tooth, pocket, probe in zip(teeth, pockets, load_probes):
        occupies_cut_cavity = (tooth & pocket).volume >= tooth.volume * 0.95
        no_wedge_penetration = (tooth & wedge).volume <= CONTACT_TOLERANCE
        load_land_volume = (probe & wedge).volume
        has_load_side_material = load_land_volume >= probe.volume * 0.60
        if occupies_cut_cavity and no_wedge_penetration and has_load_side_material:
            captured += 1
    return captured


def slider_wedge_insertion_report(samples: int = 7) -> SliderWedgeInsertionReport:
    """Sample the explicit +X to -X transverse service insertion."""
    if samples < 6:
        raise ValueError("at least six insertion samples are required")
    travel = 0.5
    wedge, _ = _slider_wedge_and_pockets(travel)
    teeth = _compound("slider_capture_teeth_check", _slider_capture_teeth(travel))
    backing = _straight_backing(travel)
    support, datum, _ = _slider_support(travel)
    approach_offset = 3.0
    max_collision = 0.0
    for index in range(samples):
        offset = approach_offset * (samples - 1 - index) / (samples - 1)
        posed_wedge = wedge.moved(Location((offset, 0.0, 0.0)))
        collision = (
            (posed_wedge & teeth).volume
            + (posed_wedge & backing).volume
            + (posed_wedge & support).volume
        )
        max_collision = max(max_collision, collision)
    wedge_box = wedge.bounding_box()
    datum_box = datum.bounding_box()
    return SliderWedgeInsertionReport(
        insertion_direction="+X toward -X",
        samples=samples,
        max_positive_collision_volume=max_collision,
        final_at_datum=abs(wedge_box.min.X - datum_box.max.X) <= CONTACT_TOLERANCE,
    )


def belt_retention_report() -> BeltRetentionReport:
    """Measure nominal-pose tooth-pocket occupancy and physical seating faces."""
    travel = 0.5
    reel_teeth = [_arc_tooth(angle) for angle in _reel_capture_angles(travel)]
    reel_wedge, reel_pockets = _reel_wedge_and_pockets(travel)
    reel_floor, reel_stop = _reel_pocket_support(travel)
    slider_teeth = _slider_capture_teeth(travel)
    slider_wedge, slider_pockets = _slider_wedge_and_pockets(travel)
    _, slider_datum, slider_stop = _slider_support(travel)

    reel_box = reel_wedge.bounding_box()
    floor_box = reel_floor.bounding_box()
    slider_box = slider_wedge.bounding_box()
    datum_box = slider_datum.bounding_box()
    return BeltRetentionReport(
        reel_wedge_captured_teeth=_captured_tooth_count(
            reel_teeth,
            reel_pockets,
            reel_wedge,
            _reel_load_probes(_reel_capture_angles(travel)),
        ),
        slider_wedge_captured_teeth=_captured_tooth_count(
            slider_teeth,
            slider_pockets,
            slider_wedge,
            _slider_load_probes(slider_teeth),
        ),
        reel_wedge_at_datum=abs(reel_box.min.Z - floor_box.max.Z) <= CONTACT_TOLERANCE,
        slider_wedge_at_datum=abs(slider_box.min.X - datum_box.max.X) <= CONTACT_TOLERANCE,
        reel_working_direction_blocked=(
            reel_wedge.distance_to(reel_stop) <= CONTACT_TOLERANCE
            and (reel_wedge & reel_stop).volume <= CONTACT_TOLERANCE
        ),
        slider_working_direction_blocked=(
            slider_wedge.distance_to(slider_stop) <= CONTACT_TOLERANCE
            and (slider_wedge & slider_stop).volume <= CONTACT_TOLERANCE
        ),
    )


def gen_step() -> Compound:
    """CAD-skill source envelope; Task 2 intentionally does not export STEP."""
    return build_belt_system(0.5)
